apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      strategy: canary
  template:
    metadata:
      labels:
        app: wordpress
        strategy: canary
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /wp-admin/install.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
